"""Assemble the single distributable sarimax_macros.sql from the layered
development files (spec section 11). The layered files in sql/ are the build
inputs; the concatenation below is what ships, and CI verifies the assembled
file matches (tests/test_assembly.py).

Usage:  python tools/build_macros.py
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

LAYERS = [
    "sql/00_linalg.sql",
    "sql/01_prep.sql",
    "sql/02_ssm.sql",
    "sql/03_filter.sql",
    "sql/04_estimate.sql",
    "sql/05_forecast.sql",
    "sql/06_harness.sql",
]

HEADER = """\
-- ============================================================================
-- duckARIMA: seasonal ARIMA with exogenous regressors (SARIMAX) as pure
-- DuckDB (>= 1.5.4) SQL table macros. No extensions, no driver required.
--
-- Load once per session:      .read sarimax_macros.sql
-- Public entry points:        sarimax_fit, sarimax_forecast, sarimax_summary,
--                             sarimax_evaluate, sarimax_residuals,
--                             sarimax_ljungbox
-- Everything prefixed _sarimax_ is internal and subject to change.
--
-- Estimation, inference and forecasting are validated against statsmodels'
-- SARIMAX: the Kalman-filter loglikelihood to near machine precision at fixed
-- parameters, fitted parameters and forecasts to optimizer tolerance (see
-- tests/ and GUIDE.md for the exact tiers).
--
-- THIS FILE IS GENERATED by tools/build_macros.py from sql/00..06 -- edit
-- those layers, not this file.
-- ============================================================================

"""


def build() -> str:
    parts = [HEADER]
    for layer in LAYERS:
        with open(os.path.join(ROOT, layer), encoding="utf-8") as f:
            src = f.read().rstrip() + "\n"
        parts.append(f"-- ================== {layer} ==================\n\n{src}\n")
    return "\n".join(parts)


if __name__ == "__main__":
    out = os.path.join(ROOT, "sarimax_macros.sql")
    with open(out, "w", encoding="utf-8", newline="\n") as f:
        f.write(build())
    print(f"wrote {out}")
